name: Pull Request

on:
  pull_request:
    branches:
      - 'main'

jobs:
  qa:
    uses: stakater/.github/.github/workflows/pull_request_doc_qa.yaml@v0.0.99
    with:
      MD_CONFIG: .github/md_config.json
      DOC_SRC: content
      MD_LINT_CONFIG: .markdownlint.yaml
  deploy_doc:
    concurrency:
      group: pull_request_versioned_doc
      cancel-in-progress: false
    uses: stakater/.github/.github/workflows/pull_request_versioned_doc.yaml@v0.0.154
    secrets:
      GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
  build:
    uses: stakater/.github/.github/workflows/pull_request_container_build.yaml@v0.0.99
    with:
      DOCKER_FILE_PATH: Dockerfile
    secrets:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      CONTAINER_REGISTRY_USERNAME: ${{ github.actor }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
